is.base.url=https://obiam:9446

# OAuth Configuration
oauth.client.id=6LU91CbY4QsoPhpnW1hySYOfipQa
oauth.client.kid=8lcKs4ZRUDxOc9AlBOJb1Izwyu0
oauth.algorithm=PS256
oauth.token.type=JWT
oauth.token.url=https://obiam:9446/oauth2/token
oauth.authorize.url=https://obiam:9446/oauth2/authorize
oauth.redirect.uri=https://obiam:9446/api-ob-demo-1.0.0/callback
oauth.state=YWlzcDozMTQ2
oauth.nonce=nonce
oauth.prompt=login
oauth.response.type=code id_token

# Open Banking API URLs
openbanking.account.base.url=https://obam:8243/open-banking/v3.1/aisp
openbanking.payment.base.url=https://obam:8243/open-banking/v3.1/pisp

cors.allowed.origin=*

# Open Banking Headers
openbanking.fapi.financial.id=open-bank

# SSL/TLS Configuration
ssl.certificate.path=/obtransport.pem
ssl.key.path=/obtransport.key
ssl.truststore.path=/client-truststore.jks
ssl.truststore.password=123456

# Backend Configuration
backend.base.url=https://obiam:9446/api-ob-demo-1.0.0/init

# Frontend Configuration
frontend.home.url=https://obiam:9446/api-ob-demo-1.0.0
